name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🛠️ Thanks for reporting your first issue! You’re officially a bug hunter — and we love having you on board!"
        pr-message: "Message that will be displayed on users' first pull request"
